### ISSUE TITLE
Game crash when put trader in vending machine

### ISSUE THREAD

**Issue by joshuaepstein** [Iskallia/Vault-public#10]
When I put a trader in the vending machine that hasn't been rolled with the trade, it crashes my game.

**Comment by Nimothy** [comment]
Hi @joshuaepstein, please could you provide your logs, this will help the developers to diagnose the problem.

**Comment by scalda** [comment]
I just tried replicating and the trader rolls on the first click of trying to get it in the vending machine but will be placed in side if i click the rolled trader.

so can you @joshuaepstein please explain what it was you did and also supply logs and crash report please

**Comment by joshuaepstein** [comment]
https://pastebin.com/R2UdfVLQ - This is the log

**Comment by Nimothy** [comment]
Hi, @joshuaepstein can you explain where you got the TraderCore from, please?

**Comment by joshuaepstein** [comment]
I got the trader core from the creative menu

**Comment by EwokHero** [comment]
Got the same problem, This is my log
[crash-2021-03-25_11.07.16-client.txt](https://github.com/Iskallia/Vault-public/files/6203923/crash-2021-03-25_11.07.16-client.txt)

**Comment by Nimothy** [comment]
Hi @joshuaepstein @EwokHero, the pack is designed to be played in survival without cheats/spawning in the_vault related items.
This crash is caused by the TraderCore lacking the correct metadata, for example, it won't have any trade. 
The developers may decide to add crash prevention.
However, from Iskall85's recent stream, he said that deliberate avoidable issues ( i.e. spawning in vault items) might not get patched.

**Comment by joshuaepstein** [comment]
Ok, thanks for the help
