### ISSUE TITLE
1490 is crashing on launch. 1424 does not crash when dropped in testing (everything else the same)

### ISSUE THREAD

**Issue by Quest79** [Iskallia/Vault-public#1213]
**Describe the bug**
1490 is crashing on launch. 1424 does not crash when dropped in testing (everything else the same)

Crash report:
https://mclo.gs/42ygQQa

Discussing it in the discord: 
https://discord.com/channels/889424759018901514/889845714207801344/1074933478723948635

Mixin related?

**Comment by Quest79** [comment]
This was done with a FRESH installation of 7.6HH + a few extra mods. 
7.6HH will **_NOT_** crash if I use 1424. But _**will**_ crash if I used 1490.

Can we get any details on what inside 1490 is causing the conflict? 


I will check the other versions available between those two versions for when this incompatibility starts.

**Comment by Quest79** [comment]
**So far:** 

the_vault-1.18.2-2.0.14.1424 : **WORKS**
the_vault-1.18.2-2.0.14.1483 : CRASH
the_vault-1.18.2-2.0.14.1487 : CRASH
the_vault-1.18.2-2.0.14.1490 : CRASH

I am using forge 40.2.1, but I have tested 40.2.0, 40.1.93, 40.1.92

**Comment by jmilthedude** [comment]
Do not use optifine with Vault Hunters. We do not support this whatsoever.

**Comment by Quest79** [comment]
Okay? As I said everything was and still is working fine with 1424 (7H). 

Compatibility broke after this. Was this on purpose?

**Comment by jmilthedude** [comment]
Then you got lucky that the pack worked for you with Optifine installed in any version. 

The point is, we have said from day one, we do not support Optifine. For as long as you have it installed, and the pack doesn’t work, we cannot help you. If you uninstall Optifine and suddenly the pack works for you, then there is nothing for us to do here. 

As for “Why?”. Optifine is developed in a way that IT does not support compatibility with anything other than Vanilla. Ask them to fix this problem and you’ll never receive an answer. Because they do things in the code that could affect other mods easily and do not think twice about it. Therefore, it does not play well with others. 

If you can run the pack, as it is shipped, and not adding mods. Then there is nothing for us to do here. Especially not adding OF, as we have said since day one we will NOT support it.

**Comment by jmilthedude** [comment]
Feel free to reopen this if you remove optifine and still have the problem.
