### ISSUE TITLE
Please remove from drop

### ISSUE THREAD

**Issue by kvermaat** [Iskallia/Vault-public#1214]
**Describe the bug**
as a server owner seeing this drop made me sweat.
you can put this in ispawner and see the world get deleted where they fly to spawn.

lucky i was the one getting the drop

**To Reproduce**
1.get Mystery Hostile Egg
2. use it
3. get lucky and get ENDER DRAGON SPAWN EGG
4. use it en cause havoc on a server, (didn't dear to try it in a ispawner cage)
5.  dragon flies and goes nom nom to spawn lowest point on cords 0, x, 0

**Expected behavior**
don't even get this item in the first place

**Screenshots or Crash Report**
Done

**Info (please complete the following information):**
- World Type: Skyvault, think on all worlds
- All versions

**Additional context**
OMG
![afbeelding_2023-02-19_173329703](https://user-images.githubusercontent.com/1015046/219961443-c95f6110-d4cf-417d-8441-26cc67265fc5.png)

**Comment by jmilthedude** [comment]
Hi, on your server, you can go into /config/the_vault/mystery_hostile_egg.json and remove the entry for cagerium:ender_dragon_spawn_egg. The entire entry, if you are unfamiliar with json, is below:
`    
{
      "value": {
        "id": "cagerium:ender_dragon_spawn_egg",
        "amountMin": 1,
        "amountMax": 1
      },
      "weight": 2
}
`
Also, since it is the last entry in the json, remove the comma just before it (at the end of the wither spawn egg entry).

This isn't really an issue. It is just a preference for your server.
