### ISSUE TITLE
GLFW error 65539: invalid key 4 when i update Vault hunter

### ISSUE THREAD

**Issue by moustache17** [Iskallia/Vault-public#1217]
**Describe the bug**
since i updated to the new 8.0.1 Update, every time i try to play its crashes and give me the GLFW error 65539: invalid key 4
**To Reproduce**
1.Update to 8.0.1
2.lunch the game
3.Error appeared

**Expected behavior**
game lunch like normally and i m abele to play the game

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 8.0.1

**Additional context**
after somme researched i found out that it my be cause i youse mouse key bind. but i don t now what to do now. how to remove mouse key bind.

PLEAS HELP ME

**Comment by d0zzer2** [comment]
Discord is the place for bug reports and fixes. Here is the info from Discord. Go to options that TXT and make this line looks like this instead of bound to your mouse.
![61F88625-F07A-4836-B51E-E0FAF5F26044](https://user-images.githubusercontent.com/36824063/225012081-12c342e7-1980-4167-874c-2ed2922266fe.png)

**Comment by moustache17** [comment]
Tanks you it work and I can finally play again
Tanks you
