### ISSUE TITLE
Statues

### ISSUE THREAD

**Issue by HoogaSwe** [Iskallia/Vault-public#13]
Game will crash when placing a Statue that been spawned in via creative/give command.

**Comment by Nimothy** [comment]
Hi @HoogaSwe, the pack is designed to be played in survival without cheats/spawning in the_vault related items/
This crash is due to the Statue not having the correct metadata. 
The developers may decide to add crash prevention. 
However, from Iskall85's recent stream, he said that deliberate avoidable issues ( i.e. spawning in statues ) might not get patched.

**Comment by KaptainWutax** [comment]
We know about this, however, the item is not designed to be picked from creative inventory, and should work fine when found in chests/loot tables, it is due to NBT tags, we won't be fixing this as of now.
