### ISSUE TITLE
Ae2 recipe issues

### ISSUE THREAD

**Issue by Abcdhary** [Iskallia/Vault-public#519]
**Describe the bug**
Fluix ME glass cables require pure fluix crystal. There is no alternative. This is an issue because the only way to get pure fluix crystal is either by unlocking mechanism or using the fluix seed. Fluix seeds require either twelve hours of sitting in water to grow or you can shorten that time with crystal growth accelerators. Only problem with that is crystal growth accelerators require Fluix ME glass cables to be made. I’m sure you can see that is a problem.
There is also some other minor issues like logic processors requiring a vault ingot while the other processors use nuggets.
And when you compare refined storage to Ae2 the recipes for the three processors cost perfect gems in Ae2 and cost no vault gems at all in refined storage.
**To Reproduce**
1.open jei 
2.search Fluix me glass cable
3.look at recipe 
4.then at chain of recipes required from there.

**Expected behavior**
I feel the requirement of only pure fluix crystals was a mistake and that you meant to leave the option of regular fluix crystals
Also you seem to have missed updating some recipes 
**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: [e.g. Single Player or Server] single player
- The_Vault Version [e.g. 1.0.1]
Latest
**Additional context**
Please fix waiting 12 hours is painful

**Comment by DaycareJr** [comment]
As far as i know this intended in this way. Get a bunch of crystals, grow them, Craft the charger thingi and with even 1 of those you should be able to get the seeds done within 20-25 minutes

**Comment by Abcdhary** [comment]
> As far as i know this intended in this way. Get a bunch of crystals, grow them, Craft the charger thingi and with even 1 of those you should be able to get the seeds done within 20-25 minutes

There is no way it’s intended that you have to wait twelve hours for crystals to grow when refined storage has nothing like that

**Comment by bsylve1996** [comment]
I can agree here since the growth accelerator has vanilla recipe and the cables have a modified recipe. The cables should require fluix crystals and not pure fluix.

**Comment by DaycareJr** [comment]
its intended ive asked 🙂 and its how the normal mod works to i beleve just get the chargers asap
________________________________
Van: Abcdhary ***@***.***>
Verzonden: dinsdag 26 oktober 2021 16:38
Aan: Iskallia/Vault-public ***@***.***>
CC: DaycareJr ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [Iskallia/Vault-public] Ae2 recipe issues (Issue #519)


As far as i know this intended in this way. Get a bunch of crystals, grow them, Craft the charger thingi and with even 1 of those you should be able to get the seeds done within 20-25 minutes

There is no way it’s intended that you have to wait twelve hours for crystals to grow when refined storage has nothing like that

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIskallia%2FVault-public%2Fissues%2F519%23issuecomment-952008257&data=04%7C01%7C%7Ca1f90f9e6c09499e002c08d9988e58f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637708559408375591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SNuT9Esy3r11JK0v8Az6kpR2UKRvJe6Rsfow80aHi0k%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPKSQD3TQYJCUGTYYHPSM33UI24QHANCNFSM5GWEUWUQ&data=04%7C01%7C%7Ca1f90f9e6c09499e002c08d9988e58f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637708559408385547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WS8R37Wjvue3qfGqzDY9Zt78HRjefkJ4dLRV%2Brwtdio%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca1f90f9e6c09499e002c08d9988e58f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637708559408385547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=28C7O1ASutFib8K9TMFEwrCJHGtZHriHoqKA24cKU88%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca1f90f9e6c09499e002c08d9988e58f9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637708559408395511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p4mJJ05fin2vf1%2BPEJ3vwiqkvJFhvk0R1lwIgZAZusA%3D&reserved=0>.

**Comment by Abcdhary** [comment]
> its intended ive asked 🙂 and its how the normal mod works to i beleve just get the chargers asap
> […](#)

That’s not how the normal mod works you can get the growth crystals without needing to get pure crystals first. The way it’s implemented in VH is insane. You shouldn’t have to wait 12 hours to get something necessary for a mod. I don’t know what your missing about it TAKES 12 HOURS, but there should be a change in the growth crystals recipe at least. You can then power one crystal without the cables which cuts the time needed from 12 hours down to like 15 min which is much more reasonable.
